# Generated by Django 6.0.5 on 2026-05-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('capacity', models.IntegerField(choices=[(10, 'Pequeño (≤10)'), (25, 'Mediano (11-25)'), (50, 'Grande (26-50)'), (100, 'Muy Grande (>50)')], verbose_name='Capacidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Piso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='infrastructure.headquarters', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['headquarters__name', 'name'],
                'unique_together': {('headquarters', 'code')},
            },
        ),
    ]
