# Generated by Django 6.0.5 on 2026-06-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='inventario',
            field=models.TextField(blank=True, null=True, verbose_name='Inventario del ambiente'),
        ),
    ]
