# Generated by Django 6.0.5 on 2026-05-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headquarters',
            options={},
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='address',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='email',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='phone',
        ),
        migrations.AlterField(
            model_name='headquarters',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='headquarters',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='headquarters',
            table='infrastructure_headquarters',
        ),
        migrations.CreateModel(
            name='environments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('headquarters_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.headquarters')),
            ],
            options={
                'db_table': 'infrastructure_environments',
            },
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
