# Generated by Django 6.0.5 on 2026-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'directory_people',
            },
        ),
    ]
