# Generated by Django 6.0.5 on 2026-05-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('directory', '0001_initial'),
        ('infrastructure', '0002_alter_headquarters_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('environments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.environments')),
                ('people_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.people')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'bookings_reserves',
                'unique_together': {('environments_id', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reserves_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reserves')),
            ],
            options={
                'db_table': 'bookings_days',
                'unique_together': {('reserves_id', 'date')},
            },
        ),
    ]
